In [3]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Load cleaned data

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
df = pd.read_csv('Cleaned_Merged_Industry_Jobs.csv')
print("Raw shape:", df.shape)
df.head()

Raw shape: (164, 29)

,Job_ID,Company,Role,Role_Group,Role_Group_Encoded,Experience_Encoded,Company_Freq,PythonRequired,LinuxRequired,NetworkingRequired,AWSRequired,AzureRequired,DockerRequired,KubernetesRequired,TerraformRequired,CyberSecurityRequired,CommunicationRequired,PythonRequired_scaled,LinuxRequired_scaled,NetworkingRequired_scaled,AWSRequired_scaled,AzureRequired_scaled,DockerRequired_scaled,KubernetesRequired_scaled,TerraformRequired_scaled,CyberSecurityRequired_scaled,CommunicationRequired_scaled,SalaryLPA_capped,SalaryLPA_capped_scaled
0,1,Capgemini,Cloud Security Engineer,Security/SOC Analyst,4,1,0.030488,5,9,8,9,6,7,9,5,8,8,-0.516353,0.753328,0.568070,0.841881,0.191171,0.364990,0.935876,-0.053804,1.333126,0.516297,9.61,1.777684
1,2,HCL,Cloud Engineer,Cloud Engineer,0,1,0.012195,7,10,8,7,9,9,5,7,7,8,0.419359,1.403569,0.568070,0.215720,1.141235,1.041357,-0.322187,0.624955,0.965058,0.516297,5.42,0.072476
2,3,Wipro,Cloud Engineer,Cloud Engineer,0,1,0.042683,6,7,8,8,5,6,6,5,7,8,-0.048497,-0.547154,0.568070,0.528800,-0.125517,0.026807,-0.007671,-0.053804,0.965058,0.516297,9.26,1.635244
3,4,Accenture,SOC Analyst,Security/SOC Analyst,4,1,0.018293,9,8,9,9,5,6,7,7,6,6,1.355070,0.103087,1.357590,0.841881,-0.125517,0.026807,0.306845,0.624955,0.596989,-1.285249,9.07,1.557920
4,5,Infosys,Cloud Security Engineer,Security/SOC Analyst,4,1,0.036585,6,6,6,8,8,8,10,9,9,6,-0.048497,-1.197395,-1.010972,0.528800,0.824547,0.703174,1.250392,1.303714,1.701194,-1.285249,8.58,1.358504

In [5]:
df.columns

Index(['Job_ID', 'Company', 'Role', 'Role_Group', 'Role_Group_Encoded', 'Experience_Encoded', 'Company_Freq', 'PythonRequired', 'LinuxRequired', 'NetworkingRequired', 'AWSRequired', 'AzureRequired',
       'DockerRequired', 'KubernetesRequired', 'TerraformRequired', 'CyberSecurityRequired', 'CommunicationRequired', 'PythonRequired_scaled', 'LinuxRequired_scaled', 'NetworkingRequired_scaled',
       'AWSRequired_scaled', 'AzureRequired_scaled', 'DockerRequired_scaled', 'KubernetesRequired_scaled', 'TerraformRequired_scaled', 'CyberSecurityRequired_scaled', 'CommunicationRequired_scaled',
       'SalaryLPA_capped', 'SalaryLPA_capped_scaled'],
      dtype='str')

## Select model features

In [6]:

df.drop(columns=['Job_ID','Company','Role','Role_Group','SalaryLPA_capped','Company_Freq','PythonRequired','LinuxRequired','NetworkingRequired','PythonRequired', 'LinuxRequired', 'NetworkingRequired', 'AWSRequired', 'AzureRequired','DockerRequired', 'KubernetesRequired', 'TerraformRequired','CyberSecurityRequired', 'CommunicationRequired'],inplace=True)
df.head()

,Role_Group_Encoded,Experience_Encoded,PythonRequired_scaled,LinuxRequired_scaled,NetworkingRequired_scaled,AWSRequired_scaled,AzureRequired_scaled,DockerRequired_scaled,KubernetesRequired_scaled,TerraformRequired_scaled,CyberSecurityRequired_scaled,CommunicationRequired_scaled,SalaryLPA_capped_scaled
0,4,1,-0.516353,0.753328,0.568070,0.841881,0.191171,0.364990,0.935876,-0.053804,1.333126,0.516297,1.777684
1,0,1,0.419359,1.403569,0.568070,0.215720,1.141235,1.041357,-0.322187,0.624955,0.965058,0.516297,0.072476
2,0,1,-0.048497,-0.547154,0.568070,0.528800,-0.125517,0.026807,-0.007671,-0.053804,0.965058,0.516297,1.635244
3,4,1,1.355070,0.103087,1.357590,0.841881,-0.125517,0.026807,0.306845,0.624955,0.596989,-1.285249,1.557920
4,4,1,-0.048497,-1.197395,-1.010972,0.528800,0.824547,0.703174,1.250392,1.303714,1.701194,-1.285249,1.358504

## Train / test split

In [7]:
x = df.drop(columns=['SalaryLPA_capped_scaled'])
y = df['SalaryLPA_capped_scaled']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## Model 1: Linear Regression (baseline)

In [9]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression()

In [10]:

y_pred = linear_model.predict(x_test)

In [11]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)
print("R2:", r2_score(y_test, y_pred))

MAE: 0.49153265300942334
RMSE: 0.6918529127722816
R2: 0.11745686429382862

## Multicollinearity check (VIF)

In [12]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [13]:
X = x.copy()

In [14]:
while True:

    vif_df = pd.DataFrame()
    vif_df['Feature'] = X.columns
    vif_df['VIF'] = [variance_inflation_factor(X.values, i)
                     for i in range(X.shape[1])]

    max_vif = vif_df['VIF'].max()

    print("\nCurrent VIF:")
    print(vif_df.sort_values('VIF', ascending=False))

    if max_vif <= 10:
        break

    feature_to_remove = vif_df.sort_values('VIF', ascending=False).iloc[0]['Feature']

    print(f"\nRemoving: {feature_to_remove} (VIF = {max_vif:.2f})")

    X = X.drop(columns=[feature_to_remove])

print("\nRemaining Features:")
print(X.columns.tolist())

Current VIF:
                         Feature       VIF
8      KubernetesRequired_scaled  5.788904
7          DockerRequired_scaled  4.425609
9       TerraformRequired_scaled  4.336508
1             Experience_Encoded  3.016615
0             Role_Group_Encoded  2.983984
2          PythonRequired_scaled  2.078560
10  CyberSecurityRequired_scaled  1.962460
3           LinuxRequired_scaled  1.911430
5             AWSRequired_scaled  1.873998
6           AzureRequired_scaled  1.710502
4      NetworkingRequired_scaled  1.340570
11  CommunicationRequired_scaled  1.172648

Remaining Features:
['Role_Group_Encoded', 'Experience_Encoded', 'PythonRequired_scaled', 'LinuxRequired_scaled', 'NetworkingRequired_scaled', 'AWSRequired_scaled', 'AzureRequired_scaled', 'DockerRequired_scaled', 'KubernetesRequired_scaled', 'TerraformRequired_scaled', 'CyberSecurityRequired_scaled', 'CommunicationRequired_scaled']

## Model 2: Random Forest

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
model_rf = RandomForestRegressor(n_estimators=200, random_state=42,max_depth=None,)

In [17]:
model_rf.fit(x_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [18]:

pred = model_rf.predict(x_test)

In [19]:
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", mean_squared_error(y_test, pred) ** 0.5)
print("R2:", r2_score(y_test, pred))

MAE: 0.3612055945851725
RMSE: 0.5901675562531383
R2: 0.357816628301056

## Model 3: Support Vector Regression

In [20]:
from sklearn.svm import SVR

In [21]:

model_svr = SVR(kernel='rbf', C=1.0, epsilon=0.1)

In [22]:
model_svr.fit(x_train, y_train) 
pred = model_svr.predict(x_test)

In [23]:

print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", mean_squared_error(y_test, pred) ** 0.5)
print("R2:", r2_score(y_test, pred))

MAE: 0.44309182191448093
RMSE: 0.6534857414980508
R2: 0.21262680425842417

## Model 4: XGBoost

In [24]:
from xgboost import XGBRegressor 
model_xg = XGBRegressor( n_estimators=100, 
                     learning_rate=0.05, 
                     subsample=0.8, 
                     colsample_bytree=0.8, 
                     random_state=42 )

In [25]:
model_xg.fit(x_train, y_train) 
pred = model_xg.predict(x_test)

In [26]:
print("MAE:", mean_absolute_error(y_test, pred))
print("RMSE:", mean_squared_error(y_test, pred) ** 0.5)
print("R2:", r2_score(y_test, pred))

MAE: 0.31979687221481173
RMSE: 0.5288314463277437
R2: 0.48436434745471113

### Conclusion

The project successfully developed a salary prediction model using multiple regression techniques. **XGBoost performed the best**, achieving an R² score of **0.4844**. Therefore, XGBoost can be selected as the final model, while more data and feature engineering could further improve prediction accuracy.

In [27]:
import joblib

joblib.dump(model_xg, "xgboost_model.pkl")

['xgboost_model.pkl']